// scripts/generate-story-imports.ts
import { readdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';

// ESM-safe __dirname
const __dirname = fileURLToPath(new URL('.', import.meta.url));

const locales = ['en', 'th'];
const baseDir = join(__dirname, '../story/content');

const output: Record<string, Record<string, string>> = {};

for (const lang of locales) {
  const langDir = join(baseDir, lang);
  const files = readdirSync(langDir).filter(f => f.endsWith('.mdx'));

  output[lang] = {};
  for (const file of files) {
    const slug = file.replace(/\.mdx$/, '');
    const importPath = `../content/${lang}/${file}`;
    output[lang][slug] = `() => import('${importPath}')`;
  }
}

const lines = [
  '// Auto-generated by generate-story-imports.ts',
  'export const storyImports = {',
];

for (const lang in output) {
  lines.push(`  ${lang}: {`);
  for (const slug in output[lang]) {
    lines.push(`    '${slug}': ${output[lang][slug]},`);
  }
  lines.push('  },');
}

lines.push('};');

const outputPath = join(__dirname, '../app/components/story-imports.ts');
writeFileSync(outputPath, lines.join('\n'), 'utf8');
